version: "3"
networks:
  dev:
services:
  son_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    networks:
      - dev
    ports:
      - "2222:22"
#    command:
#      - "-c"
#      - "sleep infinity"
    # ports:
      # - 30000:3000
    environment:
       - DOCKER_HOST="tcp://172.18.0.1:2375"
      # - SRC_ROOT=/home/admin-1/workspace/
    volumes:
      - ~/son:/home/workspace:cached